### PR TITLE
Improve script on page performance

### PR DESCRIPTION
**Pull request by akf-bw**
- Improved the performance of pages with the mollie javascript by moving it to the page head and adding the "defer" keyword to the script tag to load it already while the browser is parsing the html
- Before this PR the browser had to wait until the full parse of the script to continue parsing the page

### CODE REVIEW

**Comment by akf-bw** [comment]
I also added an additional commit to exclude the mollie script, if it is already included in the header by the default assets. This prevents duplicate mollie script tags.

**Comment by BlackScorp** [comment]
@akf-bw thx for the pull request, could you update your master? i pushed some changes to the github pipeline, your branch is out of sync

**Comment by akf-bw** [comment]
@BlackScorp done.

**Comment by BlackScorp** [comment]
@akf-bw your PR does not work, i think in shopware 6.4 there is no layout_head_javascript_hmr_mode block or the template meta.html.twig does not exists there, can you update your pr?

**Comment by akf-bw** [comment]
@BlackScorp added the include for the old 6.4 block

**Comment by BlackScorp** [comment]
@akf-bw sorry it is related, the 6.6 branch was completely green. i just started the pipeline with the current master branch https://github.com/mollie/Shopware6/actions/runs/8706312557 it will be green again

**Comment by akf-bw** [comment]
> hm.. i have to fix the pipeline first i gues

In this PR even some admin tests fail in the pipeline, even though I haven't changed anything there, so yeah I don't think this PR breaks that much compared to the master branch right now.

**Comment by akf-bw** [comment]
@BlackScorp I updated the PR to include your latest changes on the master branch. Can you rerun the pipeline so we can include this PR in the 6.6 update?

**Comment by BlackScorp** [comment]
@akf-bw i think base_hmr_mode does not exists in 6.5.5.2 and below

**Comment by akf-bw** [comment]
base_script_hmr_mode exists in v6.4.20.2 and below and was removed with 6.5
https://github.com/shopware/shopware/blob/v6.4.20.2/src/Storefront/Resources/views/storefront/base.html.twig

From 6.5 the block no longer exists, but now the layout_head_javascript_hmr_mode block exists
https://github.com/shopware/shopware/blob/v6.5.5.2/src/Storefront/Resources/views/storefront/layout/meta.html.twig

**Comment by akf-bw** [comment]
The tests fail with a "500", but I don't know where there should be a "500" error from this twig blocks
image

**Comment by akf-bw** [comment]
@BlackScorp can you please rerun the pipeline

**Comment by akf-bw** [comment]
@BlackScorp I finally fixed the issue with older versions and even improved performance again with the checks.
Could you please rerun the pipeline?

**Comment by akf-bw** [comment]
This old php versions...
I changed it.

**Comment by akf-bw** [comment]
@BlackScorp Only the "PHP CS Fixer" failed. All other tests work now 🚀
Could you please merge it and run the CS-Fixer command yourself?

**Comment by BlackScorp** [comment]
@akf-bw thx will do

**Comment by akf-bw** [comment]
@BlackScorp is there a release date for the 6.6 update?

**Pull request merged**
